---
title: "B_Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(rio)
library(readxl)
library(ggplot2)
library(scales)
library(sf)
library(magrittr)
library(plotly)

### Univariate
location="https://github.com/RSGriggs/543_proj/raw/main/"
file="WashingtonByCounty2.xls"
filelink=paste0(location,file)

data2=import(filelink)

summary(data2$AKNUE006)


data2$AKNUE006=cut(data2$AKNUE006,
                          breaks = c(0,2500,5000,10000,15000,159380),
                          labels = c("0-2500","2501-5000","5001-10000","10001-15000","More Than 15000"))

table(data2$AKNUE006)

plotW=table(data2$AKNUE006)

FreqW=as.data.frame(plotW)
names(FreqW)=c("Adolescent_Males","County_Count")
FreqW


base= ggplot(data = FreqW, 
             aes(x = Adolescent_Males,
                 y = County_Count)) 

plotz = base + geom_bar(fill ="blue",
                        stat = 'identity') 

titleText='Adolescent Males Density Distribution by Washington Counties'
sourceText='Source: American Community Survey'

plotzz = plotz + labs(title=titleText,
                     x = 'Number of Adolescent Males (6-18 Years)', 
                     y = 'Number of Counties',
                     caption = sourceText)

plotz3 = plotzz + scale_y_continuous(breaks=c(0,2,4,6,8,10,12),
                                   limits = c(0, 12),
                                   labels=unit_format(unit = NULL, accuracy = 1))

plotz4 = plotz3 + theme(plot.caption = element_text(hjust = 1), 
                      plot.title = element_text(hjust = 0.5))

plotz5 = plotz4 + geom_hline(yintercept = 7.8,
                           linetype="dashed", 
                           size=1.5,
                           alpha=0.5,
                           color="black") + annotate("text",x=3.5, y=7.8, label= "Mean of Counties",vjust= -1.5)
  
### Bivariate
location="https://github.com/RSGriggs/543_proj/raw/main/"
file="activitya.xls"
filelink=paste0(location,file)

ActivityData=import(filelink)

summary(ActivityData)

names(ActivityData)

(DatingTimespent=table(ActivityData$type_character,ActivityData$datinga))

(DatTime=prop.table(DatingTimespent,
                            margin = 2)%>%round(.,2))

DTP=as.data.frame(DatingTimespent)
names(DTP)=c("Location","Relationship","Dating")

DTP$pctCol=as.data.frame(DatTime)[,3]

head(DTP)

basea=ggplot(data=DTP, 
             aes(x=Relationship, y=pctCol,
                 fill=Location,))

baseb= basea + scale_x_discrete() 
baseb= basea + theme_classic()

Dodge1= baseb +  geom_bar(stat="identity",
                            position ='dodge') 

BiTitle='Leisure Location by Relationship Status'

Dodge2 = Dodge1 + labs(title=BiTitle,
                     x = "Relationship Status", 
                     y = NULL,
                     caption = NULL)

Dodge3 = Dodge2 + theme(plot.caption = element_text(hjust = 1), 
                      plot.title = element_text(hjust = 0.5))

Dodge4 = Dodge3 + theme(axis.ticks.y = element_blank(),
                                axis.title.y = element_blank(),
                                axis.line.y = element_blank(),
                                axis.text.y = element_blank())

ActStack = Dodge4 + geom_bar(stat = "Identity",
                              position = 'stack')

Stack1 = ActStack + scale_fill_brewer(palette="Set1")

ActStack = baseb + theme(axis.ticks.y = element_blank(),
                                axis.title.y = element_blank(),
                                axis.line.y = element_blank(),
                                axis.text.y = element_blank()) + geom_bar(stat = "Identity",
                              position = 'stack')

Stack1 = ActStack + scale_fill_brewer(palette="Set1")

Stack2 =Stack1 + geom_text(size = 5,fontface='bold',position = position_stack(vjust = 0.5),aes(label=Dating))

TText='Leisure Location by Relationship Status'
SText='Source: Major US City Survey Dataset'

Stack3 = Stack2 + labs(title=TText,
                     x = NULL, 
                     y = NULL,
                     caption = SText)

Stack4 = Stack3 + theme(plot.caption = element_text(hjust = 1), 
                      plot.title = element_text(hjust = 0.5))

### Map
TestMapFile='https://github.com/RSGriggs/543_proj/raw/main/us-states1.json'

TestMap=read_sf(TestMapFile)

str(TestMap)

CSVLink='https://github.com/RSGriggs/543_proj/raw/main/ChildrenLanguageAtHome1.csv'

CSVData=read.csv(CSVLink)

str(CSVData)

T1=ggplot(data=TestMap) + geom_sf(fill='grey90',
                                     color=NA) + theme_classic()

MapVariables=merge(TestMap,
                   CSVData, 
                   by='name')

CMap= T1 + geom_sf(data=MapVariables,
                       aes(fill=Percentage,
                           text=paste("State:",name)),
                       color=NA)

CMap2 =CMap + scale_fill_gradient(low = 'yellow',
                             high= 'blue')

CMap3 = CMap2 + theme_void()

T1Text='US Children Who Speak a Language Other Than English'
S1Text='Source: KIDS COUNT Data Center'

CMap4 = CMap3 + labs(title=T1Text,
                     x = NULL, 
                     y = NULL,
                     caption = S1Text)

CMap5 = CMap4 + theme(plot.caption = element_text(hjust = 1), 
                      plot.title = element_text(hjust = 0.5))
```

Column {data-width=250}
-----------------------------------------------------------------------

### Univariate

```{r}
plotz5
```

Column {data-width=250}
-----------------------------------------------------------------------

### Bivariate

```{r}
Stack4
```

### Map

```{r}
CMap5%>%ggplotly()
```

