IMPORT REQUIRED LIBRARIES
```{r}
library(rio)
library(readxl)
library(magrittr)
library(ggplot2)
```

IMPORT DATA
```{r}
#establish link to git repository
gitlink='https://github.com/RSGriggs/543_proj/raw/main/'
#establilsh value for dataset desired
spend='Activity_spending.xlsx'
#query excel and store as value 'act'
spend2=paste0(gitlink, spend)
#store value as datatable
spenddata=import(spend2)
```
INSPECT DATA
```{r}
#get list of column headers in actdata
names(spenddata)
```
```{r}
# checking data types
str(spenddata,width = 50,strict.width='cut')
```
```{r}
SpendingFrame=as.data.frame.matrix(spenddata)
SpendingFrame
```


BUILD DATA FRAME
#```{R}
#generate table
Destspend=table(spenddata$Destination, spenddata$Party_Size, spenddata$Avg_Spending)
#generate data frame from table
SpendingFrame=as.data.frame(Destspend)
names(SpendingFrame)=c("Destination","Party_Size", "Average_Spending")
#Add % data
SpendingFrame
#```

```{R}
#Generate base version of plot
spend1=ggplot(data=SpendingFrame,
                  aes(x=Party_Size,
                  y=Avg_Spending,
                  fill=Destination)) +
              geom_bar(stat="identity",
                      fun = 'mean',
                      position='dodge') +

                     labs(title = "Average Spending by Venue",
                          subtitle = "Catagorical and Numerical Plot",
                          tag = "check tag",
                          y = "Average $ Spent Per person",
                          x = "Number of People in Party") +
#change color
              scale_fill_brewer(palette = "Pastel2" )
#add labels
#call plot
spend1
```
