```{r}
library(ggplot2)
library(sf)
```

```{r}
TestMapFile='https://github.com/RSGriggs/543_proj/raw/main/us-states.json'
TestMap=read_sf(TestMapFile)
str(TestMap)
```

```{r}
#load merge data set 
CSVLink='https://github.com/RSGriggs/543_proj/raw/main/Smithsfavoritestates.csv'
CSVData=read.csv(CSVLink)
str(CSVData)
```

```{r}
T1=ggplot(data=TestMap) + geom_sf(fill='grey90',
                                     color=NA) + theme_classic()
T1
```

```{r}
MapVariables=merge(TestMap,
                   CSVData, 
                   by='name')

SMap= T1 + geom_sf(data=MapVariables,
                       aes(fill=Data),
                       color=NA)
SMap


SMap2 = SMap + scale_fill_gradient(low = 'gold',
                             high= 'black')
SMap2


SMap3 = SMap2 + theme_void()

SMap3


SMap4 = SMap3 + labs(title="Smith Rates the U.S. States by Arbitrary Preference.",
                     subtitle = 'The best are the brightest.',
                     x = NULL, 
                     y = NULL,
                     caption = 'R. Smith Griggs')
SMap4


SMap5 = SMap4 + theme(plot.caption = element_text(hjust = 1), 
                      plot.title = element_text(hjust = 0.5))

SMap5
```

